// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurchaseManagementSystem.Models;

namespace PurchaseManagementSystem.Migrations
{
    [DbContext(typeof(ConnectionStringClass))]
    [Migration("20221107120827_IntialCreate")]
    partial class IntialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PurchaseManagementSystem.Models.Employee", b =>
                {
                    b.Property<int>("emp_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("emp_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("emp_id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("PurchaseManagementSystem.Models.Issuance", b =>
                {
                    b.Property<int>("iss_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("emp_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("iss_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("qnty")
                        .HasColumnType("int");

                    b.HasKey("iss_id");

                    b.ToTable("issuances");
                });

            modelBuilder.Entity("PurchaseManagementSystem.Models.Item", b =>
                {
                    b.Property<int>("item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("item_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("item_status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("item_id");

                    b.ToTable("items");
                });

            modelBuilder.Entity("PurchaseManagementSystem.Models.Purchase", b =>
                {
                    b.Property<int>("pur_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("pur_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("pur_item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pur_price")
                        .HasColumnType("int");

                    b.Property<int>("pur_qnty")
                        .HasColumnType("int");

                    b.Property<string>("vendor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pur_id");

                    b.ToTable("purchases");
                });

            modelBuilder.Entity("PurchaseManagementSystem.Models.Vendor", b =>
                {
                    b.Property<int>("vendor_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("vendor_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vendor_id");

                    b.ToTable("vendors");
                });
#pragma warning restore 612, 618
        }
    }
}
